version: '3'

volumes:
  bundle:
  bundle_ruby2:

services:
  rbexy:
    build: .
    image: rbexy
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - $HOME/.ssh:/root/.ssh:ro
      - $HOME/.gitconfig:/root/.gitconfig:ro
      - $HOME/.gem/credentials:/root/.gem/credentials
    working_dir: /app
  rbexy_ruby2:
    build:
      context: .
      dockerfile: Dockerfile-ruby2
    volumes:
      - .:/app
      - bundle_ruby2:/usr/local/bundle
    working_dir: /app
  dummy:
    image: rbexy
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app/spec/dummy/
    command: ./start.sh
    ports:
      - 3000:3000
    environment:
      - RAILS_LOG_STDOUT=1
